version: 1.2
workflows:
       -  name: authorsWorkflow
          subclass: cwl
          primaryDescriptorPath: /Dockstore.cwl
          latestTagAsDefault: true
          testParameterFiles:
              - /dockstore.cwl.json
          authors:
              - name: Man without orcid
                email: test@gmail.com
                role: Not spy
                affiliation: I spy2
              - name: Man with orcid
                orcid: 00000-22222-00000
